#!/bin/bash

# get VM's IP
vm_ip=$(< ~/coreos-osx/.env/ip_address)

cmd=(ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet core@$vm_ip sudo /usr/bin/rkt "${@+$@}")

"${cmd[@]}"