
## Start - Inserted by CoreOS-Vagrant GUI App

      # Expose dockerUI port
      config.vm.network "forwarded_port", guest: 9000, host: 9000

      # Add below any other forwarded ports you might need

## End - Inserted by CoreOS-Vagrant GUI App
